name: Create GitHub Release
on:
  push:
    tags:        
      - 'v2.*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies 
        run: npm ci
      - name: Create release
        run: npx gulp createRelease:vscode-csharp --tagName ${{ github.ref_name }} --dryRun false
        env:
          GitHubPAT: ${{ secrets.GITHUB_TOKEN }}